version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "127.0.0.1:50080:80"
      - "127.0.0.1:53012:3012"
    environment:
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      DOMAIN: ${DOMAIN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SIGNUPS_VERIFY: ${SIGNUPS_VERIFY}
